### PR TITLE
German localization

### PR DESCRIPTION
**Pull request by ZweiSteinSoft**

### CODE REVIEW

**Comment by pthiess** [comment]
Assigned @jadbox -- Jonathan, we need to review this PR. While I'm grateful for the work @mynetx has done here, I want to get your perspective how this fits once we may redesign the backend. In general I'd like to see (if and?) how we want to support localization for brackets.io. Especially for German there seems to be a strong commitment to keep translations up to date. Thanks for considering this.

**Comment by jadbox** [comment]
Thanks for taking the time to do the translation to German! Was this done by hand or did you use something a translation service? Either way, it looks good to me offhand (through translation).

We need to have a proper locale system in place before we can support additional languages. Ideally we want to use a library like http://i18next.com/ that allows us to pull in the copy into a single layout. This would allow us to both easily update the site layout for all the languages as well as manage additional translations in uniform way. This work to integrate a locale library isn't being done yet, but if you have the time, you could refactor your changes into i18n compatible locale definition file. Let me know if you have the time to do so. :)

**Comment by marcelgerber** [comment]
@jadbox
I just took took a short look over this translation (no full review yet), looks very good. (I'm a native speaker)

And in case @ZweiSteinSoft has no time to convert this to be i18n compatible, I could do this as well. Just let me know.

**Comment by jadbox** [comment]
It's been awhile without any updates here. @SAPlayer, would you like to take on the task of adding i18n support to the site?

**Comment by marcelgerber** [comment]
Yes, I can take this, but it will take another while until I am ready to start.
So we use http://i18next.com, right?

**Comment by jadbox** [comment]
@SAPlayer Using i18next sounds just fine by me! Thanks so much for starting this up, just keep us updated as you go. :)

**Comment by marcelgerber** [comment]
I started the work: https://github.com/SAPlayer/brackets.io/tree/german-translation
It already works, just pull it and add `?setLng=de` to the URL.

@ingorichter @pthiess I decided to use `du` instead of `Sie` (which we use in Brackets itself). Is that ok?

**Comment by jadbox** [comment]
Wow you're quick @SAPlayer. Your branch looks great so far. Once Thiess is able to answer your question and review your branch as well, I'll be ready to merge it in when I get the green light from you. :)

**Comment by pthiess** [comment]
@SAPlayer -- Marcel, das ist grossartig! Awesome work so far:

image

Du is the right tone -- I love your engagement to make this happen @ingorichter or I will take a look as you finished translation. I'm excited to see this. Toll, gute Arbeit!

Cheers,
Peter :)

**Comment by marcelgerber** [comment]
@jadbox I'm not yet finished. Today only half of the index is translated, while I didn't even begin working on other pages like `contribute`.

**Comment by marcelgerber** [comment]
Ah yes, I've got a working demo at https://googledrive.com/host/0B986Uw1nLGY7XzNlY2hXVXI5X1U/index.html?lang=de. (You have to allow loading insecure content)
Today I did some background work (not yet on GitHub) which enables us to show the latest changes in german as well (if available) and formats the dates the german way ;) Both work great.

**Comment by pthiess** [comment]
Nice work - @SAPlayer , just a few more links... I also see an opportunity to adjust the wording a little bit, but i need to find time for a review - an example would be:

"Brackets ist ein [wie ein] Sandkasten, in dem neue Ideen und Werkzeuge ausprobiert werden. Neue Features und Erweiterungen kommen [etwa] alle 2,5 Wochen heraus."

**Comment by marcelgerber** [comment]
The visible index (not yet the requirements and installtion instructions) is finally fully translated. contribute not yet either.
I didn't ever claim my translation to be the best ever ;) I am still improving every part, and the final review (mine and yours) is still outstanding.

**Comment by pthiess** [comment]
Got it! Let me know once I (or someone else) can review ...

**Comment by marcelgerber** [comment]
Can be closed now.

**Pull request closed without merging**
