### PR TITLE
Mediaqueries to speed up page loading on mobile devices

### PR DESCRIPTION
**Pull request by marcelgerber**
This adds two new mediaqueries, which make the page load much faster on smartphones (and maybe tablets as well).

### CODE REVIEW

**Comment by ingorichter** [comment]
Assigned to @larz0. Would you mind having a quick look?

**Comment by larz0** [comment]
Looks good, merging.

**Comment by ingorichter** [comment]
Hi, this looks a little bit weird on my Android phone:
Was this intended?
screenshot_2014-05-23-16-04-19

**Comment by ingorichter** [comment]
BTW: I'm using Chrome 35

**Comment by marcelgerber** [comment]
It works on my Android phone (Chrome 35) in both Landscape and Portrait mode... Are you still seeing it?

**Comment by larz0** [comment]
@SAPlayer could it be due to @media only screen and (-webkit-min-device-pixel-ratio: 2),
  only screen and (min-device-pixel-ratio: 2) ?

**Comment by marcelgerber** [comment]
@larz0 Ah yes, you're right, could repro it with Screen emulation. Will fix it now.

**Pull request merged**
