### PR TITLE
changed update url to location in S3 Bucket

### PR DESCRIPTION
**Pull request by ingorichter**
Required for the update notification url change.

### CODE REVIEW

**Comment by bchintx** [comment]
Done with review.  Merging.

**Comment by marcelgerber** [comment]
I'm not seeing the new features in Chrome 35, but the file itself is being loaded.

**Comment by marcelgerber** [comment]
@ingorichter We can't simply remove the update notification files because Sprint 39 is relying on them. We need at least a redirect.

**Comment by ingorichter** [comment]
Restoring the update notification files for release 39 builds.

**Pull request merged**
