### PR TITLE
Update normalize.css

### PR DESCRIPTION
**Pull request by coliff**
Updated to Normalize v3.0.3
Used minified version for smaller file size / faster loading

### CODE REVIEW

**Comment by ficristo** [comment]
Could you use the not minimized file?

**Comment by coliff** [comment]
Would it not be better to use the minified version for production though? The larger filesize impacts load times. https://developers.google.com/speed/pagespeed/insights/?url=brackets.io

**Comment by ficristo** [comment]
I was going to reconsider my decision but I just checked the normalize repo doesn't offer the minified version and sincerly I don't like that the minified step wasn't part of our build.
Since we don't have a build system and I really doubt the minification could save much, I still prefer the non minified version.

**Comment by coliff** [comment]
cool. no problem. I'll update my PR

**Comment by coliff** [comment]
This PR can be closed now as I opened a new one:
https://github.com/adobe/brackets.io/pull/186

**Pull request closed without merging**
