### PR TITLE
Show spinner while loading version info.

### PR DESCRIPTION
**Pull request by marcelgerber**
This is for adobe/brackets#7857.

### CODE REVIEW

**Comment by TomMalbran** [comment]
I think that it would be better to remove the initial features and just show the spinner instead of adding an opacity to the column as it is mentioned in adobe/brackets#7857.

**Comment by marcelgerber** [comment]
Hm, I vote for preserving them as there are several scenarios where loading takes long or won't even happen.
Think of one with a mobile and slow network connection. Think of one with IE6, think of one with JS disabled (those two are basically the same :P). Think of one from a more poor country than the US or Germany, like India, where I guess the internet is slower.

**Comment by TomMalbran** [comment]
The issue is not a problem of not loading, but a problem of showing updates for an old Sprint that have nothing to do with the current Release. We don't really need to display these old updates. It might be a lot more useful to initially show a link to the release pages in GitHub and later replace that with the current notes. Same could be done with the Recent blog posts.

If you have JavaScript disabled you are stuck with the loading icon and an opacity over the old content, so I don't that is better than just showing the loading icon. If JavaScript disabled is an issue,  which at this point it shouldn't, then the loading icon should be added with JavaScript.

**Comment by njx** [comment]
Agree with @TomMalbran.

**Comment by marcelgerber** [comment]
I agree, will change it tomorrow.

**Comment by marcelgerber** [comment]
@njx @TomMalbran Committed the change.

**Comment by larz0** [comment]
@SAPlayer @TomMalbran this looks good. We should merge this once the conflict is fixed (my bad).

**Comment by marcelgerber** [comment]
@larz0 Fixed & squashed.

**Comment by larz0** [comment]
Looks good, merging. Thanks @SAPlayer!

**Pull request merged**
