### PR TITLE
BIG contribute page update. Now with 200% less JavaScript!

### PR DESCRIPTION
**Pull request by adrocknaphobia**
Updated all the marketing copy on the page. Re-wrote the dynamic calls to Github and Trello. Removed CoffeeScript generated crap, jQuery plugins, mustache.js, require.js, text.js and other crap.

### CODE REVIEW

**Comment by GarthDB** [comment]
So glad. I hate all the hipster webdev crap.

**Comment by adrocknaphobia** [comment]
@GarthDB I was using document.getElementById before it was cool.

**Comment by GarthDB** [comment]
so true.

**Comment by njx** [comment]
Drive-by: looks like you're not escaping the text you're pulling from Trello/GitHub, so if there are ampersands or less-than signs in any of it, it might break the page.

**Pull request merged**
