### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Denisov21**
Correct a small error!

### CODE REVIEW

**Comment by marcelgerber** [comment]
It doesn't make any difference, does it?

**Comment by Denisov21** [comment]
In HTML, the file path should be, for example href = "img/test.jpg" or href ="../test.jpg"

**Comment by marcelgerber** [comment]
Actually, `/img/test.jpg` is also valid and commonly used. It's relative to root. (http://stackoverflow.com/a/5559597/3455922)

**Comment by Denisov21** [comment]
@SAPlayer Hi, ok. I think close this PR!

**Pull request closed without merging**
