### PR TITLE
[homepage] Add missing space

### PR DESCRIPTION
**Pull request by 0b10011**
> Made with ♥and JavaScript

Should be:

> Made with ♥ and JavaScript

### CODE REVIEW

**Comment by larz0** [comment]
Thanks @bfrohs, merging. :+1:

**Comment by ingorichter** [comment]
@bfrohs Did you sign the Brackets CLA?

**Comment by 0b10011** [comment]
@ingorichter I don't believe so---I wasn't aware I needed to. Is [this the CLA](http://dev.brackets.io/brackets-contributor-license-agreement.html) I should sign?

**Comment by larz0** [comment]
@bfrohs yes that's the one.

**Comment by 0b10011** [comment]
Signed!

**Comment by larz0** [comment]
batman-thumbs-up

**Comment by ingorichter** [comment]
@bfrohs Thank you!

**Pull request merged**
