### PR TITLE
Removing references to Extract

### PR DESCRIPTION
**Pull request by bet-cio**
Quick clean-up to remove references to Extract before the service is decommissioned.

### CODE REVIEW

**Comment by bet-cio** [comment]
Added a new commit changing localized string structure as well. Unfortunately would mean English strings in the other locales until we can get help translating them.

**Comment by marcelgerber** [comment]
I wanted to clean this up before but forgot about it, so good thing you came to help :)

As the translation automatically falls back to English, I think it's best not to add English strings to the translation files. You can still remove strings and parts of strings.

I will provide a German translation as soon as this lands, and I will ping our translators so they can contribute, too.

**Comment by bet-cio** [comment]
Thanks for the help with the translations, Marcel!

I had a chance to review the changes in person with Ryan, so I'll get this merged.

**Comment by abose** [comment]
Just noticed the change in the site, the new hero image of brackets does not seem to be the stock user experience for brackets with a different theme applied and a couple of additional 'extension' buttons. Wouldn't int be better to put in the image of stock brackets as the hero image. It would be confusing for new users to see the program they downloaded does not seem to be the one in the screenshot?

**Comment by abose** [comment]
Created issue https://github.com/adobe/brackets.io/issues/183 tracking this.

**Pull request merged**
