### PR TITLE
load json rss feed directly from blog.brackets.io

### PR DESCRIPTION
**Pull request by ingorichter**
without taking the yql route anymore. Adding message to indicate that blog posts couldn't be updated and page needs to be refreshed in order to load them

### CODE REVIEW

**Comment by ingorichter** [comment]
@larz0 Would you mind reviewing this and merge it when you are happy with it? Thanks!

**Comment by larz0** [comment]
Thanks @ingorichter I can see the message: 

screen shot 2014-02-07 at 10 30 59 am

**Comment by ingorichter** [comment]
@larz0 Sorry man. I've fixed this.

**Comment by larz0** [comment]
Schweet!

**Pull request merged**
