### PR TITLE
Add info alert on WinXP

### PR DESCRIPTION
**Pull request by marcelgerber**
**Screens:**
English:

German:

@larz0 Are the colors ok?

### CODE REVIEW

**Comment by peterflynn** [comment]
@MarcelGerber Should we also do this for Mac OS X pre-10.6.8 and for Debian 7?  We actually get confusion over Debian 7 far more often than we do with Win XP...

For Debian, we could have the info link point to: https://github.com/adobe/brackets/issues/4816

**Comment by marcelgerber** [comment]
@peterflynn That'd indeed be cool, but I guess we'd need two different alert texts, one specifically for XP (mentioning the blog post) and another for everything else (old OS X, Debian, Win 2000), probably linking to the [Requirements page](https://github.com/adobe/brackets/wiki/Troubleshooting#requirements) or to the requirements modal (which doesn't even mention Linux, btw).
But I presumably won't get to that part until Monday.

**Comment by larz0** [comment]
@MarcelGerber can we replace the button with that notification, make the background transparent and add a 1px solid white border?

**Comment by peterflynn** [comment]
@larz0 That seems nice -- as long as the "Other Downloads" link is still accessible, in case we mis-detect their OS.

@MarcelGerber Having a generic banner for the others seems fair.  For Debian specifically though, it would be good to have a link to the bug I cited above -- since that seems to be the number one source of 'wrong OS' confusion for Brackets.

**Comment by larz0** [comment]
@peterflynn yep we're not removing those links :+1:

**Comment by marcelgerber** [comment]
@larz0 I also thought about coloring the "Requirements" button sinde they don't fit. What about that?

**Comment by larz0** [comment]
@MarcelGerber not sure what you meant, could you take a screenshot of "Requirements" not fitting? I'm assuming that we don't need to touch those three links below the download button.

**Comment by marcelgerber** [comment]
@larz0 Disregard that. It was a bad idea :D

**Comment by marcelgerber** [comment]
@larz0 Looks awesome :)


@peterflynn Detects some more now.

**Comment by larz0** [comment]
@MarcelGerber thanks that looks great! @peterflynn can review the code. :+1:

**Comment by marcelgerber** [comment]
@ingorichter Could you take a look at this?

**Comment by ingorichter** [comment]
@MarcelGerber Sure, I'll do this after the meeting and the lunch break.

**Comment by ingorichter** [comment]
That was a long lunch break. I'm going to review this Friday morning.

**Comment by ingorichter** [comment]
Thank you.

**Pull request merged**
