### PR TITLE
Tweaks.

### PR DESCRIPTION
**Pull request by larz0**

### CODE REVIEW

**Comment by larz0** [comment]
Thanks @yomi0. We need to hide it based on the device and not screen size.

@adrocknaphobia thoughts?

**Comment by GarthDB** [comment]
Topcoat is hiding it based on screen size and it seems to work alright.

**Comment by larz0** [comment]
What size do you recommend?

**Comment by GarthDB** [comment]
I believe it is either 880px or 940px.

**Comment by larz0** [comment]
That will probably show up on landscape mode on certain devices.

**Comment by GarthDB** [comment]
940 might work but you're right.

I wonder if there's something in modernizr for this.

**Comment by larz0** [comment]
Paul Irish recommended http://detector.dmolsen.com

**Comment by GarthDB** [comment]
Never argue with the Irish.

**Comment by larz0** [comment]
DULY NOTED.

**Pull request merged**
