### PR TITLE
Update to Release 1.3

### PR DESCRIPTION
**Pull request by prafulVaishnav**

### CODE REVIEW

**Comment by peterflynn** [comment]
Just a note for anyone else who's confused by this: we don't actually have a final build yet, and won't be merging this until the build is all set (e.g. see [release tasks](https://github.com/adobe/brackets/issues/10860)).  ETA is Monday, I think.

**Comment by prafulVaishnav** [comment]
Will open it again when we will be close to release.

**Comment by nethip** [comment]
Since this is just a PR we can keep this open. We will merge this on Monday immediately after posting the builds.

**Comment by nethip** [comment]
Looks good! Merging.

**Pull request merged**
