### PR TITLE
Fix issue with "New Features" in other languages

### PR DESCRIPTION
**Pull request by marcelgerber**
For #106 
As most changes are whitespace changes, try reviewing with https://github.com/adobe/brackets.io/pull/108/files?w=0

### CODE REVIEW

**Comment by marcelgerber** [comment]
Conflicts resolved (sorry for not keeping the history, but I found rebasing was easier than resolving conflicts).

**Comment by marcelgerber** [comment]
I'd like to have this merged in before Release 1.0 in order to have a great website/download experience for _all_ countries - currently, it does only work correctly for languages that have translated Release Notes available.
cc @ingorichter could you take a look?

**Comment by ingorichter** [comment]
Let me check this over the weekend. I need to see if there are any conflicting changes with the new brackets.io design (currently not checked in, since it contains something that is not yet announced)

**Comment by marcelgerber** [comment]
Updated & resolved conflicts.

**Comment by ingorichter** [comment]
I have tried it, but it doesn't work for me when I pass `lang=de` or `lang=fr`. The browser always appends a `/` and `shortLocale` always results in `de/` or `fr/`. It works fine, if I append `lang=de-DE`, because `requestedLang.split("-")[0]` cuts off everything after the `-` (and the trailing `/` too). This means that `shortLocale` has to be sanitized before continuing loading the appropriate translation.

**Comment by marcelgerber** [comment]
@ingorichter Even though I cannot reproduce your issue (what browser do you use? Chrome?), I tried to fix it.

**Comment by ingorichter** [comment]
@MarcelGerber I've tried it with Firefox and Chrome. I don't know why it behaves this way, but that's what I can experience.

**Comment by ingorichter** [comment]
@MarcelGerber It works now. Thanks.

**Comment by ingorichter** [comment]
Funny, the `/` only gets appened when I test it with my local web server. Testing with the published `brackets.io` site doesn't add the `/`.

**Pull request merged**
