### PR TITLE
Foundation 5

### PR DESCRIPTION
**Pull request by marcelgerber**
Updating from Foundation 4.3.2 to Foundation 5.2.2
Demo: https://googledrive.com/host/0B986Uw1nLGY7XzNlY2hXVXI5X1U/index.html

### CODE REVIEW

**Comment by ingorichter** [comment]
I noticed some minor layout differences. Is this intended?
- Font looks differently
- Alignment at the bottom (Get Involved, Videos, Quick Links). Header is not aligned with left border of list anymore

I think we should add another responsive breakpoint, to make the site look better on mobile devices too. Currently it seems, that on a small screen the top of the page doesn't adapt properly to the screen size.

screenshot 2014-05-21 08 34 41

**Comment by marcelgerber** [comment]
@ingorichter I forgot to say you should make sure to enable insecure content in Chrome in order to actually load the Webfonts.
There are not too much visual changes at first glance, the only one I saw is the Download button, but imho it looks better now.
You're correct, the list's style changed and looks weird, but we can easily patch it with a single rule in our stylesheet.

But I don't get what you're wanting the mobile page to look like - in my opinion, it looks very good. Notice the Download button won't appear on "normal" mobile devices (Android/iOS).

**Comment by ingorichter** [comment]
Yeah, the insecure content... ;-) Let me check this again
For the mobile page...forget what I said. It seems, that the pages look differently when viewed on mobile devices vs. narrow desktop browser windows. That was causing my previous comment.

**Comment by marcelgerber** [comment]
Well, one question on the PR itself - shall I completely remove the `js/foundation/` folder? I only updated the files because they were there before, but we don't even need them as they are all included in the minified file.

**Comment by larz0** [comment]
@SAPlayer I can take a look tomorrow or something. Thanks!

**Comment by larz0** [comment]
@SAPlayer assigning this to myself.

**Comment by larz0** [comment]
@SAPlayer looks good here. The only thing that needs to be fixed is the "Download Brackets" font, that button is using Helvetica for some reason.

screen shot 2014-05-22 at 4 54 45 pm

**Comment by marcelgerber** [comment]
@larz0 Fixed in the latest commit, as well as the list margin issue.

**Comment by larz0** [comment]
@SAPlayer thanks. Merging.

**Pull request merged**
