### PR TITLE
Only display 8 blog posts

### PR DESCRIPTION
**Pull request by marcelgerber**
Works.

### CODE REVIEW

**Comment by TomMalbran** [comment]
I was going to suggest using `data.slice(0, 8).forEach(function (item, index) { ... })`

**Comment by marcelgerber** [comment]
@TomMalbran But that will cause issues if there will ever be less than 8 blog posts (don't know how that could happen, but always be aware!)

**Comment by peterflynn** [comment]
@MarcelGerber It should work fine even in that case -- e.g. `[1,2,3].slice(0,8)` yields `[1,2,3]` without error.

**Comment by marcelgerber** [comment]
You're right. Change pushed.

**Comment by larz0** [comment]
Merging.

**Pull request merged**
