### PR TITLE
Show YouTube videos in a modal dialog

### PR DESCRIPTION
**Pull request by marcelgerber**
Demo: https://googledrive.com/host/0B986Uw1nLGY7XzNlY2hXVXI5X1U/index.html
Just click on any YouTube video (there are five) and you'll see a dialog, at least if you're not on mobile.

### CODE REVIEW

**Comment by TomMalbran** [comment]
This is cool, but I find the modal a bit small for YouTube videos. At that size I might even prefer to go to YouTube to see them. What about making them larger (like 800px wide), and a bit more responsive (to shrink to 500-600px before it is not displayed again)? When using a bigger size you might need to check if it not too tall.

Also I noticed that the modals are no longer centered in the screen. I think that the recent update to foundation added the box-sizing property to all elements, so we no longer need to add the padding to the negative margin left in https://github.com/adobe/brackets.io/blob/gh-pages/css/reveal.css#L35

**Comment by marcelgerber** [comment]
@TomMalbran I updated it. Still not perfect, but better imo.

**Comment by TomMalbran** [comment]
It is better, but it now seems to get so big that I need to scroll to center it in the screen. Hehe.

**Comment by marcelgerber** [comment]
I see, but do you know how to fix that issue? Unfortunately I got no idea :(

**Comment by TomMalbran** [comment]
I think the easiest solution is to add a max width. But that might break the center alignment, so maybe you need to have a fixed width class that becomes percentage with with a media query.

That should hopefully fix the issue, but if not you will need JavaScript to change the width.

**Comment by marcelgerber** [comment]
~~I already tried `max-width` on both `.reveal-modal` and `.flex-video`, both did unfortunately just fail.~~

E: Oh well, looks like I only tested `max-height`, which doesn't work indeed, but `max-width` works :+1:

**Comment by marcelgerber** [comment]
@TomMalbran Next attempt, now calculating in JS, which works pretty well. The only thing still causing issues is the Foundation media queries...

**Comment by larz0** [comment]
Looks good on iPhone and iPad, merging.

**Pull request merged**
